/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:4ad07c1f-fa9b-4a2e-913a-82c80fd95c2f",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_qx1wCukUl",
    "aws_user_pools_web_client_id": "4octvovcia1mhsjqusaol1jget",
    "oauth": {}
};


export default awsmobile;
